DJANGO_SETTINGS_MODULE=cognitive.settings
DJANGO_SECRET_KEY="secret key"
DJANGO_ALLOWED_HOSTS="*"
DJANGO_DEBUG=True

POSTGRES_PASSWORD=mysecretpass
POSTGRES_USER=postgres
POSTGRES_NAME=postgres
POSTGRES_HOST=postgres
POSTGRES_PORT=5432
